export const CHANGE_JSON_PLACEHOLDER_DATA = 'app/CHANGE_JSON_PLACEHOLDER_DATA';
export const CHANGE_JSON_PLACEHOLDER_DATA_STATUS =
  'app/CHANGE_JSON_PLACEHOLDER_DATA_STATUS';

export const SET_NAME = 'app/SET_NAME';
